2024-11-23 13:15:55,895 - {'optimizer': {'name': 'adam', 'lr': 0.001, 'weight_decay': 0}, 'train': {'epoch': 500, 'batch_size': 4096, 'save_model': False, 'loss': 'pairwise', 'log_loss': False, 'test_step': 3, 'patience': 5, 'reproducible': True, 'seed': 2023, 'early_stop': True}, 'test': {'metrics': ['recall', 'ndcg'], 'k': [10, 20, 40], 'batch_size': 1024}, 'data': {'type': 'social', 'name': 'yelp', 'user_num': 43043, 'item_num': 66576}, 'model': {'name': 'idea_lightgcn', 'layer_num': 2, 'reg_weight': 1e-08, 'embedding_size': 64, 'self_gating_unit': True, 'pagerank': True, 'combine_gcn': False, 'alpha': 0.8, 'cl_weight': 1e-05, 'sigma': 20}, 'tune': {'enable': True, 'hyperparameters': ['layer_num', 'reg_weight', 'cl_weight', 'alpha'], 'layer_num': [2, 3], 'reg_weight': [1e-06, 1e-07, 1e-08], 'cl_weight': [1e-05, 1e-06, 1e-07], 'alpha': [0.7, 0.8, 0.9]}, 'device': 'cuda', 'log': True}
2024-11-23 13:15:55,895 - hyperparameter: {'layer_num': 2, 'reg_weight': 1e-06, 'cl_weight': 1e-05, 'alpha': 0.7}
2024-11-23 13:16:00,322 - CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 47.54 GiB of which 1024.00 KiB is free. Including non-PyTorch memory, this process has 47.52 GiB memory in use. Of the allocated memory 47.16 GiB is allocated by PyTorch, and 50.64 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/doyunchoi/ds535/trainer/utils.py", line 15, in wrapper
    return func(*args, **kwargs)
  File "/home/doyunchoi/ds535/trainer/trainer.py", line 128, in train
    self.train_epoch(model, epoch_idx)
  File "/home/doyunchoi/ds535/trainer/trainer.py", line 79, in train_epoch
    loss, loss_dict = model.cal_loss(batch_data)
  File "/home/doyunchoi/ds535/models/social/idea_lightgcn.py", line 350, in cal_loss
    user_embeds, item_embeds = self.forward()
  File "/home/doyunchoi/ds535/models/social/idea_lightgcn.py", line 324, in forward
    trust_adj = self.get_trust_adj(self.trust_mat, self.adj, embeds)
  File "/home/doyunchoi/ds535/models/social/idea_lightgcn.py", line 279, in get_trust_adj
    trust_influence_mat = self._get_trust_influence_mat(trust_mat, user_embeds_first_gcn)
  File "/home/doyunchoi/ds535/models/social/idea_lightgcn.py", line 233, in _get_trust_influence_mat
    block = squared_block_i - 2 * user_block_i @ user_block_j.T + squared_block_j.T
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 47.54 GiB of which 1024.00 KiB is free. Including non-PyTorch memory, this process has 47.52 GiB memory in use. Of the allocated memory 47.16 GiB is allocated by PyTorch, and 50.64 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
